baseURL = "https://www.kevinguay.com/"
languageCode = "en-us"
title = "Kevin Guay"
theme = "blue"
disqusShortname = "kevinguay"
googleAnalytics = "UA-109988049-1"

[params]
  subtitle = "Kevin Guay's programming blog."
  author = "Kevin Guay"